language: ruby
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: mK4Dsh6Qtx1W5ZL4z8KEmnC7VYBVwR7bjTMZYN1Aa3A4gRbJw+cEs5VwEuLSYxjK38rQUBxXHzTMvGCHzLbOXoy/ewVzKLPa3HpWHfni3BQ63vBsXbzV5UFCJalrnx3x+NtiREdwpS+EhOA7+/CDeSgJYrmFzA/h0QvmGYj04qFbv8PNJENLi4+torzAYKIkA6Pa1zor9I/sZQRysjAgHpER5EsAdjSt2kHtkGnu9BCAgjpN0M0cLs/arVPa4m8JDtPHGsVuWJH3a3P+RHeYDKjQej4cr3/BH9VojARfAdBaD5p1bkDQv5Juh7h28gVxxcACm6qWjj0VQr2wDIoRhbYellAIppgvCy4oZ5NGgGkQUOx2bkB/FR5YmPTYnpWQTKIggKCQObyVLJVbGGV/tndyW2ntv/1AxQgeSzNcti4SrIrhyp1GBMsOHMmy9vXi1UtdA5xH8aAaERotOKu7yEFUL2rRKL8lCAzHTRCetd+jobJP6k0pEq3/SGWlAGuMcLBWbvTJe1oti7VqYO3wq/uK+Lop5qZ1BSkHx8RyIrSWJHWN3KZ5LAdK9N2zw9OuhW/GwroxaxX11Faw4K+3yAzfjHB133ogledq9XExQ//8kHpJ6TlWDsElbOH8N4IxH54bLY9B1d3lZVHmr6Xmk1nfPtC8slDHlrvIEJ1cDqc=
  - secure: QvtmeELb/0oJy+Za+o8ymJSfJZDbxwCUQT5m55FNuqVSjXqm6JPD42Q84+P4hLgV5scor3xHmBCj4JNJ45AXyMHpxTI8x9g8wCdMMQjKnF7YNMmzut9f4bxtDplyW31cv6XlueV/we//tb9X4VxHh7+eEyj1Bh1eT4vpZdrR8eazQ8JzX1ST368CN91qft4Ia2+xvxmNodb6mAbPz5jhfYdy457w/1a674qLzuxv8O/Dqt+SAb6qXIbdSpBh9U1xrG6aQYTTlatK+rsvaOtbaR5k9iy8tn0wQOomkgPNNnEZwlNCGHxXMj4BW6dyZgDvwWtOTkI/FmBVtPs4xlwNtV3UBjSaOFIMDWZk2q6I8VKcUhSVe4OyUo/NJZItieqkQIhavFEgL/bCO3nV8bddj+aj0hlXCfYpGranfZeUgal5EHskA4kTbM6vfzJlx3Mjl3lJD0Fq9Gk8sm4g3BMS268YZzYPp7UWUrZdrdd8k8M1P+4QqeWneK9VCnd+BEOOvTGl4XaOl16dAXubomP49ox10U98qhe77OLzRgfVl8kiUwQD0LLIGBuqdv+q/ru3pRiv5CoVFT1OYiHdSW6C3JOtVVwVXwVb6RxwymNJ2RM9rRakNZXx5hYEp3tJcNplYz6DDzv5foWKQbAD00374pq2+NjCGBmQIHyVsNfwyhU=
sudo: false
exclude:
- vendor
branches:
  only:
  - master
