language: ruby
rvm:
- 2.6.3
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: VNvaOK1on1/Hb9Rel3xLcSRNa3Rv0g3ZnCnuDwfXs5orCBtpm3KaPFGuwplKhhLtq9tjj2U+28qCPTU81JqDnB+TTCDgntTA+doiZE3j7Mj22ywqbw1nkw3puaxrrJOZ5HHP+IrnaKhPppzPNhc1Kz7LjH1gNMgY9X3W3zCo1PB8KqHi2JTq15iRd5ugpaJLWSwbaPF15OjCzHbU2B6KlFyHziUg4OwJCQ/R2Y24/BzbjoJuQHk7/AXvwTvtVTmg2NHC2qJUeitfpi1ekpAjfzlrUrgcBcud52TXHG9iUg8lAzZQkmufXDRf6lBDEJR2gWogxEb4obubN9He5quEXhx77kD/lFODSfjxMuE8WMf4FgJRWldpgHw892STWDOpkNBBE3qxG/MvHzGH3pg29eyvdvxu3PjCg0QHfUV4oLBdIhhUtLqbNRV0Upc2YmueuuEl2LOvbQ9o4iSMmPtEh3yOISxf+SjOLXWYZEwULoydoPBMpVQAEAVW96uQy+ZiBjvSjj68wfZ9KQ4P24PpxQ5345g7m0msmReKGTjYoRhWSjFkjPbmwlIIvR/l46pEPdzxhtbzdqvA1xfCd7T3M8+rtIip/iRoBsfHvHq+YjzbZmaV/y+EWZDW0MgsoHy5YiFoff3GOw5Xoz8GRFlDCAjT/D00qe8Sj64hlecZMiM=
sudo: false
exclude:
- vendor
branches:
  only:
  - master
