# Site settings
title: 科技引领未来
description: 这是一个计算机科学与技术专业的知识和经验分享博客
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "" # the subpath of your site, e.g. /blog/ or / for root
url: "https://201910089194.github.io" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 全站关闭开关，在这里被关闭它根本就不能运行
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  #设置为'true'启用分页调试。这可以在站点配置中启用，也可以只对单个分页页面启用
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy #隐私权政策


permalink: /:title


# Google Analytics 逻辑分析的方法
analytics_id: ""

# Build settings 构建设置
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: 201910089194 #github username
repo: 201910089194.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://201910089194.github.io/
source_url:  https://github.com/201910089194/201910089194.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml